# Generated by Django 5.2.5 on 2025-12-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_time', models.CharField(blank=True, choices=[('morning', 'Morning (9am - 12pm)'), ('afternoon', 'Afternoon (12pm - 5pm)'), ('evening', 'Evening (5pm - 8pm)')], max_length=20, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('exterior', 'Exterior painting'), ('interior', 'Interior painting'), ('both', 'Both interior & exterior'), ('commercial', 'Commercial project')], max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
